import type { TransactionCardData } from "../components/transactions/TransactionCard";

export const demoTransactions: TransactionCardData[] = [
  {
    id: "1",
    title: "MTN Airtime",
    description: "0803 123 4567",
    date: "10:24 AM",
    dateGroup: "Today",
    amount: -500,
    status: "success",
    category: "airtime",
  },
  {
    id: "2",
    title: "Wallet Top-up",
    description: "Bank transfer (GTBank)",
    date: "9:05 AM",
    dateGroup: "Today",
    amount: 50000,
    status: "success",
    category: "wallet",
  },
  {
    id: "3",
    title: "Airtel Data",
    description: "0812 987 6543",
    date: "4:12 PM",
    dateGroup: "Yesterday",
    amount: -1200,
    status: "success",
    category: "data",
  },
  {
    id: "4",
    title: "IKEDC Electricity",
    description: "Meter 45012345678",
    date: "6:40 PM",
    dateGroup: "Yesterday",
    amount: -8500,
    status: "pending",
    category: "electricity",
  },
  {
    id: "5",
    title: "DSTV Compact",
    description: "Decoder 7031234567",
    date: "2:15 PM",
    dateGroup: "This week",
    amount: -8700,
    status: "failed",
    category: "tv",
  },
  {
    id: "6",
    title: "Glo Airtime",
    description: "0805 555 1212",
    date: "11:30 AM",
    dateGroup: "This week",
    amount: -200,
    status: "success",
    category: "airtime",
  },
];
